
json_example = {   u'current_page': 0,
    u'documents': [   {   u'authors': [   {   u'forename': u'G G',
                                              u'surname': u'Kaplan'},
                                          {   u'forename': u'C',
                                              u'surname': u'Hur'},
                                          {   u'forename': u'J',
                                              u'surname': u'Korzenik'},
                                          {   u'forename': u'B E',
                                              u'surname': u'Sands'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-dose-escalation-vs-initiation-adalimumab-loss-response-crohns-disease-cost-effectiveness/',
                          u'publication_outlet': u'Alimentary Pharmacology & Therapeutics',
                          u'title': u"Infliximab dose escalation vs. initiation of adalimumab for loss of response in Crohn's disease: a cost-effectiveness analysis.",
                          u'uuid': u'd35b34a0-6d08-11df-a2b2-0026b95e3eb7',
                          u'year': 2007},
                      {   u'authors': [   {   u'forename': u'A N',
                                              u'surname': u'Ananthakrishnan'},
                                          {   u'forename': u'C',
                                              u'surname': u'Hur'},
                                          {   u'forename': u'J R',
                                              u'surname': u'Korzenik'}],
                          u'doi': u'10.1007/s10620-011-1896-3',
                          u'mendeley_url': u'http://www.mendeley.com/research/certolizumab-pegol-compared-natalizumab-patients-moderate-severe-crohns-disease-results-decision-ana/',
                          u'publication_outlet': u'Dig Dis Sci',
                          u'title': u"Certolizumab pegol compared to natalizumab in patients with moderate to severe Crohn's disease: results of a decision analysis",
                          u'uuid': u'0905f840-baa2-11e1-909c-0024e8453de6',
                          u'year': 2012},
                      {   u'authors': [   {   u'forename': u'Corey A',
                                              u'surname': u'Siegel'},
                                          {   u'forename': u'Chin',
                                              u'surname': u'Hur'},
                                          {   u'forename': u'Joshua R',
                                              u'surname': u'Korzenik'},
                                          {   u'forename': u'G Scott',
                                              u'surname': u'Gazelle'},
                                          {   u'forename': u'Bruce E',
                                              u'surname': u'Sands'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/risks-benefits-infliximab-treatment-crohns-disease/',
                          u'publication_outlet': u'Clinical gastroenterology and hepatology the official clinical practice journal of the American Gastroenterological Association',
                          u'title': u"Risks and benefits of infliximab for the treatment of Crohn's disease.",
                          u'uuid': u'454adae0-6d02-11df-afb8-0026b95d30b2',
                          u'year': 2006},
                      {   u'authors': [   {   u'forename': u'Gianpaolo',
                                              u'surname': u'Parrilli'},
                                          {   u'forename': u'Luigi',
                                              u'surname': u'Orsini'},
                                          {   u'forename': u'Michela',
                                              u'surname': u'Corsaro'},
                                          {   u'forename': u'Maria A',
                                              u'surname': u'Bianco'},
                                          {   u'forename': u'Pietro',
                                              u'surname': u'Coccoli'},
                                          {   u'forename': u'Maria Lucia',
                                              u'surname': u'Garofano'},
                                          {   u'forename': u'Gianluca G',
                                              u'surname': u'Rotondano'},
                                          {   u'forename': u'Livio',
                                              u'surname': u'Cipolletta'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-severe-gastrointestinal-bleeding-crohns-disease/',
                          u'publication_outlet': u'Inflammatory Bowel Diseases',
                          u'title': u"Infliximab for severe gastrointestinal bleeding in Crohn's disease.",
                          u'uuid': u'ca8da290-6d08-11df-a2b2-0026b95e3eb7',
                          u'year': 2006},
                      {   u'authors': [   {   u'forename': u'Bruce E',
                                              u'surname': u'Sands'},
                                          {   u'forename': u'Frank H',
                                              u'surname': u'Anderson'},
                                          {   u'forename': u'Charles N',
                                              u'surname': u'Bernstein'},
                                          {   u'forename': u'William Y',
                                              u'surname': u'Chey'},
                                          {   u'forename': u'Brian G',
                                              u'surname': u'Feagan'},
                                          {   u'forename': u'Richard N',
                                              u'surname': u'Fedorak'},
                                          {   u'forename': u'Michael A',
                                              u'surname': u'Kamm'},
                                          {   u'forename': u'Joshua R',
                                              u'surname': u'Korzenik'},
                                          {   u'forename': u'Bret A',
                                              u'surname': u'Lashner'},
                                          {   u'forename': u'Jane E',
                                              u'surname': u'Onken'},
                                          {   u'forename': u'Daniel',
                                              u'surname': u'Rachmilewitz'},
                                          {   u'forename': u'Paul',
                                              u'surname': u'Rutgeerts'},
                                          {   u'forename': u'Gary',
                                              u'surname': u'Wild'},
                                          {   u'forename': u'Douglas C',
                                              u'surname': u'Wolf'},
                                          {   u'forename': u'Paul A',
                                              u'surname': u'Marsters'},
                                          {   u'forename': u'Suzanne B',
                                              u'surname': u'Travers'},
                                          {   u'forename': u'Marion A',
                                              u'surname': u'Blank'},
                                          {   u'forename': u'Sander J',
                                              u'surname': u'Van Deventer'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-maintenance-therapy-fistulizing-crohns-disease/',
                          u'publication_outlet': u'The New England Journal of Medicine',
                          u'title': u"Infliximab maintenance therapy for fistulizing Crohn's disease.",
                          u'uuid': u'60b1df80-6d08-11df-afb8-0026b95d30b2',
                          u'year': 2004},
                      {   u'authors': [   {   u'forename': u'S',
                                              u'surname': u'Schneeweiss'},
                                          {   u'forename': u'J',
                                              u'surname': u'Korzenik'},
                                          {   u'forename': u'D H',
                                              u'surname': u'Solomon'},
                                          {   u'forename': u'C',
                                              u'surname': u'Canning'},
                                          {   u'forename': u'J',
                                              u'surname': u'Lee'},
                                          {   u'forename': u'B',
                                              u'surname': u'Bressler'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-other-immunomodulating-drugs-patients-inflammatory-bowel-disease-risk-serious-bacterial-i/',
                          u'publication_outlet': u'Alimentary Pharmacology & Therapeutics',
                          u'title': u'Infliximab and other immunomodulating drugs in patients with inflammatory bowel disease and the risk of serious bacterial infections.',
                          u'uuid': u'427ba030-6d00-11df-afb8-0026b95d30b2',
                          u'year': 2009},
                      {   u'authors': [   {   u'forename': u'Joshua R',
                                              u'surname': u'Korzenik'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/crohns-disease-future-anti-tumor-necrosis-factor-therapies-beyond-infliximab-1/',
                          u'publication_outlet': u'Gastroenterology Clinics Of North America',
                          u'title': u"Crohn's disease: future anti-tumor necrosis factor therapies beyond infliximab.",
                          u'uuid': u'827aaeb0-6d00-11df-a2b2-0026b95e3eb7',
                          u'year': 2004},
                      {   u'authors': [   {   u'forename': u'Hiroko',
                                              u'surname': u'Kunitake'},
                                          {   u'forename': u'Richard',
                                              u'surname': u'Hodin'},
                                          {   u'forename': u'Paul C',
                                              u'surname': u'Shellito'},
                                          {   u'forename': u'Bruce E',
                                              u'surname': u'Sands'},
                                          {   u'forename': u'Joshua',
                                              u'surname': u'Korzenik'},
                                          {   u'forename': u'Liliana',
                                              u'surname': u'Bordeianou'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/perioperative-treatment-infliximab-patients-crohns-disease-ulcerative-colitis-not-associated-increased-rate-postoperative-complications/',
                          u'publication_outlet': u'Journal of gastrointestinal surgery official journal of the Society for Surgery of the Alimentary Tract',
                          u'title': u"Perioperative treatment with infliximab in patients with Crohn's disease and ulcerative colitis is not associated with an increased rate of postoperative complications.",
                          u'uuid': u'89727d10-6d05-11df-a2b2-0026b95e3eb7',
                          u'year': 2008},
                      {   u'authors': [   {   u'forename': u'Leonard',
                                              u'surname': u'Baidoo'},
                                          {   u'forename': u'Gary R',
                                              u'surname': u'Lichtenstein'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/next-after-infliximab/',
                          u'publication_outlet': u'American Journal of Gastroenterology',
                          u'title': u'What next after infliximab?',
                          u'uuid': u'e22afd60-6d00-11df-a474-0026b95e3e23',
                          u'year': 2005},
                      {   u'authors': [   {   u'forename': u'A',
                                              u'surname': u'Swaminath'},
                                          {   u'forename': u'T',
                                              u'surname': u'Ullman'},
                                          {   u'forename': u'M',
                                              u'surname': u'Rosen'},
                                          {   u'forename': u'L',
                                              u'surname': u'Mayer'},
                                          {   u'forename': u'S',
                                              u'surname': u'Lichtiger'},
                                          {   u'forename': u'M T',
                                              u'surname': u'Abreu'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/early-clinical-experience-adalimumab-treatment-inflammatory-bowel-disease-infliximab-treated-na\xefve-p/',
                          u'publication_outlet': u'Alimentary Pharmacology & Therapeutics',
                          u'title': u'Early clinical experience with adalimumab in treatment of inflammatory bowel disease with infliximab-treated and na\xefve patients.',
                          u'uuid': u'597961d0-6d07-11df-a2b2-0026b95e3eb7',
                          u'year': 2009},
                      {   u'authors': [   {   u'forename': u'A',
                                              u'surname': u'Perdriger'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-treatment-rheumatoid-arthritis-1/',
                          u'publication_outlet': u'Rheumatic Diseases Clinics Of North America',
                          u'title': u'Infliximab in the treatment of rheumatoid arthritis',
                          u'uuid': u'e48d7710-6d03-11df-afb8-0026b95d30b2',
                          u'year': 2009},
                      {   u'authors': [   {   u'forename': u'James A',
                                              u'surname': u'Richter'},
                                          {   u'forename': u'Stephen J',
                                              u'surname': u'Bickston'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-luminal-crohns-disease/',
                          u'publication_outlet': u'Gastroenterology Clinics Of North America',
                          u'title': u"Infliximab use in luminal Crohn's disease.",
                          u'uuid': u'f5451900-6d03-11df-a474-0026b95e3e23',
                          u'year': 2006},
                      {   u'authors': [   {   u'forename': u'Gert',
                                              u'surname': u'Van Assche'},
                                          {   u'forename': u'S\xe9verine',
                                              u'surname': u'Vermeire'},
                                          {   u'forename': u'Vera',
                                              u'surname': u'Ballet'},
                                          {   u'forename': u'Frederik',
                                              u'surname': u'Gabriels'},
                                          {   u'forename': u'Maja',
                                              u'surname': u'Noman'},
                                          {   u'forename': u'Geert',
                                              u'surname': u"D'Haens"},
                                          {   u'forename': u'Christophe',
                                              u'surname': u'Claessens'},
                                          {   u'forename': u'Evelien',
                                              u'surname': u'Humblet'},
                                          {   u'forename': u'Niels',
                                              u'surname': u'Vande Casteele'},
                                          {   u'forename': u'Ann',
                                              u'surname': u'Gils'},
                                          {   u'forename': u'Paul',
                                              u'surname': u'Rutgeerts'}],
                          u'doi': u'10.1136/gutjnl-2011-300755',
                          u'mendeley_url': u'http://www.mendeley.com/research/switch-adalimumab-patients-crohns-disease-controlled-maintenance-infliximab-prospective-randomised-switch-trial/',
                          u'publication_outlet': u'Gut',
                          u'title': u"Switch to adalimumab in patients with Crohn's disease controlled by maintenance infliximab: prospective randomised SWITCH trial.",
                          u'uuid': u'f3cc3a40-1a27-11e1-b17d-0024e8453de6',
                          u'year': 2011},
                      {   u'authors': [   {   u'forename': u'',
                                              u'surname': u'M Chaparro'},
                                          {   u'forename': u'P',
                                              u'surname': u'Mart\xednez-Montiel'},
                                          {   u'forename': u'M',
                                              u'surname': u'Van Domselaar'},
                                          {   u'forename': u'F',
                                              u'surname': u'Bermejo'},
                                          {   u'forename': u'J L',
                                              u'surname': u'P\xe9rez-Calle'},
                                          {   u'forename': u'B',
                                              u'surname': u'Casis'},
                                          {   u'forename': u'A L\xf3pez-San',
                                              u'surname': u'Rom\xe1n'},
                                          {   u'forename': u'A',
                                              u'surname': u'Algaba'},
                                          {   u'forename': u'J',
                                              u'surname': u'Mat\xe9'},
                                          {   u'forename': u'J P',
                                              u'surname': u'Gisbert'}],
                          u'doi': u'10.1016/j.crohns.2011.07.005',
                          u'mendeley_url': u'http://www.mendeley.com/research/intensification-infliximab-therapy-crohns-disease-efficacy-safety/',
                          u'publication_outlet': u'Journal of Crohns colitis',
                          u'title': u"Intensification of infliximab therapy in Crohn's disease: efficacy and safety.",
                          u'uuid': u'784243a0-0457-11e1-b17d-0024e8453de6',
                          u'year': 2012},
                      {   u'authors': [   {   u'forename': u'Y-f',
                                              u'surname': u'Chen'},
                                          {   u'forename': u'P',
                                              u'surname': u'Jobanputra'},
                                          {   u'forename': u'P',
                                              u'surname': u'Barton'},
                                          {   u'forename': u'S',
                                              u'surname': u'Jowett'},
                                          {   u'forename': u'S',
                                              u'surname': u'Bryan'},
                                          {   u'forename': u'W',
                                              u'surname': u'Clark'},
                                          {   u'forename': u'A',
                                              u'surname': u'Burls'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/adalimumab-etanercept-infliximab-treatment-rheumatoid-arthritis/',
                          u'publication_outlet': u'Business',
                          u'title': u'Adalimumab, etanercept and infliximab for the treatment of rheumatoid arthritis',
                          u'uuid': u'715933b0-f3d1-11df-a785-0024e8453de6',
                          u'year': 2006},
                      {   u'authors': [   {   u'forename': u'Ashwin N',
                                              u'surname': u'Ananthakrishnan'},
                                          {   u'forename': u'Chin',
                                              u'surname': u'Hur'},
                                          {   u'forename': u'Pascal',
                                              u'surname': u'Juillerat'},
                                          {   u'forename': u'Joshua R',
                                              u'surname': u'Korzenik'}],
                          u'doi': u'10.1038/ajg.2011.237',
                          u'mendeley_url': u'http://www.mendeley.com/research/strategies-prevention-postoperative-recurrence-crohns-disease-results-decision-analysis/',
                          u'publication_outlet': u'American Journal of Gastroenterology',
                          u'title': u"Strategies for the prevention of postoperative recurrence in Crohn's disease: results of a decision analysis.",
                          u'uuid': u'4b04f340-ae5e-11e1-909c-0024e8453de6',
                          u'year': 2011},
                      {   u'authors': [   {   u'forename': u'Emilie',
                                              u'surname': u'Ducourau'},
                                          {   u'forename': u'Denis',
                                              u'surname': u'Mulleman'},
                                          {   u'forename': u'Gilles',
                                              u'surname': u'Paintaud'},
                                          {   u'forename': u'Delphine Chu',
                                              u'surname': u'Miow Lin'},
                                          {   u'forename': u'Francine',
                                              u'surname': u'Lauf\xe9ron'},
                                          {   u'forename': u'David',
                                              u'surname': u'Ternant'},
                                          {   u'forename': u'Herv\xe9',
                                              u'surname': u'Watier'},
                                          {   u'forename': u'Philippe',
                                              u'surname': u'Goupille'}],
                          u'doi': u'10.1186/ar3386',
                          u'mendeley_url': u'http://www.mendeley.com/research/antibodies-toward-infliximab-associated-low-infliximab-concentration-treatment-initiation-poor-infliximab-maintenance-rheumatic-diseases/',
                          u'publication_outlet': u'Arthritis research therapy',
                          u'title': u'Antibodies toward infliximab are associated with low infliximab concentration at treatment initiation and poor infliximab maintenance in rheumatic diseases.',
                          u'uuid': u'feb47720-e920-11e0-9df2-0024e8453de6',
                          u'year': 2011},
                      {   u'authors': [   {   u'forename': u'D W',
                                              u'surname': u'Hommes'},
                                          {   u'forename': u'B',
                                              u'surname': u'Oldenburg'},
                                          {   u'forename': u'A A',
                                              u'surname': u'Van Bodegraven'},
                                          {   u'forename': u'R A',
                                              u'surname': u'Van Hogezand'},
                                          {   u'forename': u'D J',
                                              u'surname': u'De Jong'},
                                          {   u'forename': u'M J L',
                                              u'surname': u'Romberg-Camps'},
                                          {   u'forename': u'J',
                                              u'surname': u'Van Der Woude'},
                                          {   u'forename': u'G',
                                              u'surname': u'Dijkstra'}],
                          u'doi': u'10.1136/pmj.77.909.436',
                          u'mendeley_url': u'http://www.mendeley.com/research/infliximab-treatment-crohns-disease-1/',
                          u'publication_outlet': u'The Netherlands journal of medicine',
                          u'title': u"Infliximab treatment for Crohn's disease",
                          u'uuid': u'ab25af20-6d02-11df-a2b2-0026b95e3eb7',
                          u'year': 2001},
                      {   u'authors': [   {   u'forename': u'Adrienne',
                                              u'surname': u'Youdim'},
                                          {   u'forename': u'Eric A',
                                              u'surname': u'Vasiliauskas'},
                                          {   u'forename': u'Stephan R',
                                              u'surname': u'Targan'},
                                          {   u'forename': u'Konstantinos A',
                                              u'surname': u'Papadakis'},
                                          {   u'forename': u'Andrew',
                                              u'surname': u'Ippoliti'},
                                          {   u'forename': u'Marla C',
                                              u'surname': u'Dubinsky'},
                                          {   u'forename': u'Juan',
                                              u'surname': u'Lechago'},
                                          {   u'forename': u'Jane',
                                              u'surname': u'Paavola'},
                                          {   u'forename': u'Jaime',
                                              u'surname': u'Loane'},
                                          {   u'forename': u'Susie K',
                                              u'surname': u'Lee'},
                                          {   u'forename': u'Joanne',
                                              u'surname': u'Gaiennie'},
                                          {   u'forename': u'Katie',
                                              u'surname': u'Smith'},
                                          {   u'forename': u'Jason',
                                              u'surname': u'Do'},
                                          {   u'forename': u'Maria T',
                                              u'surname': u'Abreu'}],
                          u'doi': None,
                          u'mendeley_url': u'http://www.mendeley.com/research/pilot-study-adalimumab-infliximab-allergic-patients/',
                          u'publication_outlet': u'Inflammatory Bowel Diseases',
                          u'title': u'A pilot study of adalimumab in infliximab-allergic patients.',
                          u'uuid': u'3bde4580-6d09-11df-a2b2-0026b95e3eb7',
                          u'year': 2004},
                      {   u'authors': [   {   u'forename': u'Ase',
                                              u'surname': u'Riis'},
                                          {   u'forename': u'Tom C',
                                              u'surname': u'Martinsen'},
                                          {   u'forename': u'Helge L',
                                              u'surname': u'Waldum'},
                                          {   u'forename': u'Reidar',
                                              u'surname': u'Fossmark'}],
                          u'doi': u'10.3109/00365521.2012.672591',
                          u'mendeley_url': u'http://www.mendeley.com/research/clinical-experience-infliximab-adalimumab-single-center-cohort-patients-crohns-disease/',
                          u'publication_outlet': u'Scandinavian Journal of Gastroenterology',
                          u'title': u"Clinical experience with infliximab and adalimumab in a single-center cohort of patients with Crohn's disease.",
                          u'uuid': u'746a91b0-a50b-11e1-909c-0024e8453de6',
                          u'year': 2012}],
    u'items_per_page': 20,
    u'total_pages': 347510,
    u'total_results': 6950185}