test_article = {   u'entrezajax': {   u'error': False},
    u'result': [   {   u'MedlineCitation': 
                        {   u'Article': {   u'Abstract': {   u'AbstractText': [   u"We have identified multiple distinct splicing enhancer elements within protein-coding sequences of the constitutively spliced human beta-globin pre-mRNA. Each of these highly conserved sequences is sufficient to activate the splicing of a heterologous enhancer-dependent pre-mRNA. One of these enhancers is activated by and binds to the SR protein SC35, whereas at least two others are activated by the SR protein SF2/ASF. A single base mutation within another enhancer element inactivates the enhancer but does not change the encoded amino acid. Thus, overlapping protein coding and RNA recognition elements may be coselected during evolution. These studies provide the first direct evidence that SR protein-specific splicing enhancers are located within the coding regions of constitutively spliced pre-mRNAs. We propose that these enhancers function as multisite splicing enhancers to specify 3' splice-site selection."]},
                                                               u'Affiliation': u'Department of Molecular and Cellular Biology, Harvard University, Cambridge, Massachusetts 02138, USA.',
                                                               u'ArticleDate': [   ],
                                                               u'ArticleTitle': u'Multiple distinct splicing enhancers in the protein-coding sequences of a constitutively spliced pre-mRNA.',
                                                               u'AuthorList': [   {   u'ForeName': u'T D',
                                                                                      u'Identifier': [   ],
                                                                                      u'Initials': u'TD',
                                                                                      u'LastName': u'Schaal'},
                                                                                  {   u'ForeName': u'T',
                                                                                      u'Identifier': [   ],
                                                                                      u'Initials': u'T',
                                                                                      u'LastName': u'Maniatis'}],
                                                               u'ELocationID': [   ],
                                                               u'GrantList': [   {   u'Acronym': u'GM',
                                                                                     u'Agency': u'NIGMS NIH HHS',
                                                                                     u'Country': u'United States',
                                                                                     u'GrantID': u'GM42231'}],
                                        u'Journal': {   u'ISOAbbreviation': u'Mol. Cell. Biol.',
                                                       u'ISSN': u'0270-7306',
                                                       u'JournalIssue': {   u'Issue': u'1',
                                                                            u'PubDate': {   u'Month': u'Jan',
                                                                                            u'Year': u'1999'},
                                                                            u'Volume': u'19'},
                                                                            u'Title': u'Molecular and cellular biology'},
                                                               u'Language': [   u'eng'],
                                                               u'Pagination': {   u'MedlinePgn': u'261-73'},
                                                               u'PublicationTypeList': [   u'Journal Article',
                                                                                           u"Research Support, U.S. Gov't, P.H.S."]},
                                               u'ChemicalList': [   {   u'NameOfSubstance': u'Cross-Linking Reagents',
                                                                        u'RegistryNumber': u'0'},
                                                                    {   u'NameOfSubstance': u'Nuclear Proteins',
                                                                        u'RegistryNumber': u'0'},
                                                                    {   u'NameOfSubstance': u'RNA Precursors',
                                                                        u'RegistryNumber': u'0'},
                                                                    {   u'NameOfSubstance': u'RNA-Binding Proteins',
                                                                        u'RegistryNumber': u'0'},
                                                                    {   u'NameOfSubstance': u'Ribonucleoproteins',
                                                                        u'RegistryNumber': u'0'},
                                                                    {   u'NameOfSubstance': u'SRSF2 protein, human',
                                                                        u'RegistryNumber': u'147153-65-9'},
                                                                    {   u'NameOfSubstance': u'serine-arginine-rich splicing proteins',
                                                                        u'RegistryNumber': u'170974-22-8'},
                                                                    {   u'NameOfSubstance': u'Globins',
                                                                        u'RegistryNumber': u'9004-22-2'}],
                                               u'CitationSubset': [u'IM'],
                                               u'CommentsCorrectionsList': [   {   u'PMID': u'1589782',
                                                                                   u'RefSource': u'Science. 1992 May 15;256(5059):992-7'},
                                                                               {   u'PMID': u'9536098',
                                                                                   u'RefSource': u'Hum Mol Genet. 1998 May;7(5):919-32'},
                                                                               {   u'PMID': u'1825520',
                                                                                   u'RefSource': u'Science. 1991 Mar 1;251(4997):1045-50'},
                                                                               {   u'PMID': u'1834932',
                                                                                   u'RefSource': u'Mol Cell Biol. 1991 Dec;11(12):5919-28'},
                                                                               {   u'PMID': u'1944277',
                                                                                   u'RefSource': u'Mol Cell Biol. 1991 Dec;11(12):6075-83'},
                                                                               {   u'PMID': u'2136768',
                                                                                   u'RefSource': u'Mol Cell Biol. 1990 Jan;10(1):84-94'},
                                                                               {   u'PMID': u'2247057',
                                                                                   u'RefSource': u'Mol Cell Biol. 1990 Dec;10(12):6299-305'},
                                                                               {   u'PMID': u'2427200',
                                                                                   u'RefSource': u'Cell. 1986 Aug 29;46(5):681-90'},
                                                                               {   u'PMID': u'2837425',
                                                                                   u'RefSource': u'Genes Dev. 1988 Mar;2(3):319-29'},
                                                                               {   u'PMID': u'2968159',
                                                                                   u'RefSource': u'Cell. 1988 Jun 17;53(6):949-61'},
                                                                               {   u'PMID': u'2994004',
                                                                                   u'RefSource': u'Nucleic Acids Res. 1985 Aug 12;13(15):5591-609'},
                                                                               {   u'PMID': u'3352607',
                                                                                   u'RefSource': u'Mol Cell Biol. 1988 Feb;8(2):860-6'},
                                                                               {   u'PMID': u'3649340',
                                                                                   u'RefSource': u'J Biol Chem. 1987 Aug 15;262(23):11284-91'},
                                                                               {   u'PMID': u'6828386',
                                                                                   u'RefSource': u'Nucleic Acids Res. 1983 Mar 11;11(5):1475-89'},
                                                                               {   u'PMID': u'7489484',
                                                                                   u'RefSource': u'RNA. 1995 Mar;1(1):21-35'},
                                                                               {   u'PMID': u'7493322',
                                                                                   u'RefSource': u'RNA. 1995 Oct;1(8):763-71'},
                                                                               {   u'PMID': u'7540101',
                                                                                   u'RefSource': u'Curr Biol. 1995 Mar 1;5(3):249-51'},
                                                                               {   u'PMID': u'7585252',
                                                                                   u'RefSource': u'RNA. 1995 Sep;1(7):663-80'},
                                                                               {   u'PMID': u'7761834',
                                                                                   u'RefSource': u'Science. 1995 May 26;268(5214):1173-6'},
                                                                               {   u'PMID': u'7852296',
                                                                                   u'RefSource': u'J Biol Chem. 1995 Feb 10;270(6):2411-4'},
                                                                               {   u'PMID': u'7867927',
                                                                                   u'RefSource': u'Genes Dev. 1995 Feb 1;9(3):284-93'},
                                                                               {   u'PMID': u'7935481',
                                                                                   u'RefSource': u'Mol Cell Biol. 1994 Nov;14(11):7670-82'},
                                                                               {   u'PMID': u'7958850',
                                                                                   u'RefSource': u'Genes Dev. 1994 Jul 15;8(14):1703-12'},
                                                                               {   u'PMID': u'7962048',
                                                                                   u'RefSource': u'J Cell Biol. 1994 Nov;127(3):593-607'},
                                                                               {   u'PMID': u'8089127',
                                                                                   u'RefSource': u'J Biol Chem. 1994 Sep 23;269(38):23590-6'},
                                                                               {   u'PMID': u'8124712',
                                                                                   u'RefSource': u'Cell. 1994 Feb 25;76(4):735-46'},
                                                                               {   u'PMID': u'8139654',
                                                                                   u'RefSource': u'Nature. 1994 Mar 10;368(6467):119-24'},
                                                                               {   u'PMID': u'8223480',
                                                                                   u'RefSource': u'EMBO J. 1993 Dec;12(12):4715-26'},
                                                                               {   u'PMID': u'8223481',
                                                                                   u'RefSource': u'EMBO J. 1993 Dec;12(12):4727-37'},
                                                                               {   u'PMID': u'8253386',
                                                                                   u'RefSource': u'Genes Dev. 1993 Dec;7(12A):2405-17'},
                                                                               {   u'PMID': u'8261509',
                                                                                   u'RefSource': u'Cell. 1993 Dec 17;75(6):1061-70'},
                                                                               {   u'PMID': u'8276242',
                                                                                   u'RefSource': u'Genes Dev. 1993 Dec;7(12B):2598-608'},
                                                                               {   u'PMID': u'8289812',
                                                                                   u'RefSource': u'Mol Cell Biol. 1994 Feb;14(2):1347-54'},
                                                                               {   u'PMID': u'8334698',
                                                                                   u'RefSource': u'Cell. 1993 Jul 16;74(1):105-14'},
                                                                               {   u'PMID': u'8449402',
                                                                                   u'RefSource': u'Genes Dev. 1993 Mar;7(3):407-18'},
                                                                               {   u'PMID': u'9649504',
                                                                                   u'RefSource': u'Genes Dev. 1998 Jul 1;12(13):1998-2012'},
                                                                               {   u'PMID': u'1285125',
                                                                                   u'RefSource': u'Genes Dev. 1992 Dec;6(12B):2554-68'},
                                                                               {   u'PMID': u'1566072',
                                                                                   u'RefSource': u'Science. 1992 Apr 10;256(5054):237-40'},
                                                                               {   u'PMID': u'1577277',
                                                                                   u'RefSource': u'Genes Dev. 1992 May;6(5):837-47'},
                                                                               {   u'PMID': u'8524796',
                                                                                   u'RefSource': u'Proc Natl Acad Sci U S A. 1995 Dec 5;92(25):11524-8'},
                                                                               {   u'PMID': u'8647433',
                                                                                   u'RefSource': u'Genes Dev. 1996 Jun 1;10(11):1356-68'},
                                                                               {   u'PMID': u'8668147',
                                                                                   u'RefSource': u'Mol Cell Biol. 1996 Jul;16(7):3317-26'},
                                                                               {   u'PMID': u'8682289',
                                                                                   u'RefSource': u'Genes Dev. 1996 Jul 1;10(13):1569-79'},
                                                                               {   u'PMID': u'8722179',
                                                                                   u'RefSource': u'Curr Opin Genet Dev. 1996 Apr;6(2):215-20'},
                                                                               {   u'PMID': u'8743883',
                                                                                   u'RefSource': u'Curr Opin Cell Biol. 1996 Jun;8(3):331-9'},
                                                                               {   u'PMID': u'8769651',
                                                                                   u'RefSource': u'Genes Dev. 1996 Aug 15;10(16):2089-101'},
                                                                               {   u'PMID': u'9030686',
                                                                                   u'RefSource': u'Genes Dev. 1997 Feb 1;11(3):334-44'},
                                                                               {   u'PMID': u'9108022',
                                                                                   u'RefSource': u'Proc Natl Acad Sci U S A. 1997 Apr 15;94(8):3596-601'},
                                                                               {   u'PMID': u'9115432',
                                                                                   u'RefSource': u'Curr Opin Genet Dev. 1997 Apr;7(2):205-11'},
                                                                               {   u'PMID': u'9159075',
                                                                                   u'RefSource': u'Curr Opin Cell Biol. 1997 Jun;9(3):350-7'},
                                                                               {   u'PMID': u'9418892',
                                                                                   u'RefSource': u'Mol Cell Biol. 1998 Jan;18(1):450-8'},
                                                                               {   u'PMID': u'1620124',
                                                                                   u'RefSource': u'Mol Cell Biol. 1992 Jul;12(7):3165-75'}],
                                               u'DateCompleted': {   u'Day': u'10',
                                                                     u'Month': u'02',
                                                                     u'Year': u'1999'},
                                               u'DateCreated': {   u'Day': u'10',
                                                                   u'Month': u'02',
                                                                   u'Year': u'1999'},
                                               u'DateRevised': {   u'Day': u'17',
                                                                   u'Month': u'11',
                                                                   u'Year': u'2011'},
                                               u'GeneralNote': [],
                                               u'KeywordList': [],
                                               u'MedlineJournalInfo': {   u'Country': u'UNITED STATES',
                                                                          u'ISSNLinking': u'0270-7306',
                                                                          u'MedlineTA': u'Mol Cell Biol',
                                                                          u'NlmUniqueID': u'8109087'},
                                               u'MeshHeadingList': [   {   u'DescriptorName': u'Cross-Linking Reagents',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'Enhancer Elements, Genetic',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'Exons',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'Globins',
                                                                           u'QualifierName': [   u'genetics']},
                                                                       {   u'DescriptorName': u'Humans',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'Nuclear Proteins',
                                                                           u'QualifierName': [   u'genetics',
                                                                                                 u'metabolism']},
                                                                       {   u'DescriptorName': u'RNA Precursors',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'RNA Splicing',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'RNA-Binding Proteins',
                                                                           u'QualifierName': [   ]},
                                                                       {   u'DescriptorName': u'Ribonucleoproteins',
                                                                           u'QualifierName': [   ]}],
                                               u'OtherAbstract': [],
                                               u'OtherID': [u'PMC83884'],
                                               u'PMID': u'9858550',
                                               u'SpaceFlightMission': []},
                       u'PubmedData': {   u'ArticleIdList': [   u'9858550',
                                                                u'PMC83884'],
                                          u'History': [   {   u'Day': u'22',
                                                              u'Month': u'12',
                                                              u'Year': u'1998'},
                                                          {   u'Day': u'22',
                                                              u'Hour': u'0',
                                                              u'Minute': u'1',
                                                              u'Month': u'12',
                                                              u'Year': u'1998'},
                                                          {   u'Day': u'22',
                                                              u'Hour': u'0',
                                                              u'Minute': u'0',
                                                              u'Month': u'12',
                                                              u'Year': u'1998'}],
                                          u'PublicationStatus': u'ppublish'}}]}
