#
# Replace a title in XLS with the title pubmed
# e.g.   'A New Family of Candidate Pheromone Receptors in Mammals'
#became: 'A novel family of candidate pheromone receptors in mammals'
#

TITLE_UPDATE_DICT = {'A Superhelical Spiral in E. coli DNA Gyrase A C-terminal Domain Imparts Unidirectional Supercoiling Bias':'A superhelical spiral in the Escherichia coli DNA gyrase A C-terminal domain imparts unidirectional supercoiling bias'
,'ATR is Not Required for p53 Activation but Synergizes with p53 in the Replication Checkpoint':'ATR is not required for p53 activation but synergizes with p53 in the replication checkpoint'
,'All-Atom Model for Stabilization of Cross-Linked Peptides':'All-atom model for stabilization of alpha-helical structure in peptides by hydrocarbon staples'
,'Anaphase Inactiviation of the Spindle Checkpoint':'Anaphase inactivation of the spindle checkpoint'
,'Binding and Stability Determinants of the PPARgamma Nuclear Receptor/Coactivator Interface as Revealed by Shotgun Alanine Scanning and in vivo Selection':'Binding and stability determinants of the PPARgamma nuclear receptor-coactivator interface as revealed by shotgun alanine scanning and in vivo selection'
,'CARS Microscopy: Lights Up Lipids in Living Cells':'title'
,'Checkpoint Silencing During the DNA Damage Response in C. elegans Embryos':'Checkpoint silencing during the DNA damage response in Caenorhabditis elegans embryos'
,'Chemical Genetic Modifier Screens: Small Molecule Trichostatin Suppressors as Probes of Acetylation in Transcription, Cell Cycle Progression, and Stability of the Cytoskeleton':'Chemical genetic modifier screens: small molecule trichostatin suppressors as probes of intracellular histone and tubulin acetylation'
,'DNA Glycosylase Recognition and Catalysis':'DNA glycosylase recognition and catalysis'
,'Direct Inhibition of the Notch Transactivation Complex with Stapled Peptides in T-ALL':'Direct inhibition of the NOTCH transcription factor complex'
,'Directed Evolution Approaches to the Study of Proteins':'Dissecting protein structure and function using directed evolution'
,'Directed Evolution of a Molecular Switch: Small Molecule-Dependent Protein Splicing':'Directed evolution of ligand dependence: Small-molecule-activated protein splicing'
,'Discovery of Specific Hepatitis C Virus Life Cycle Inhibitors by Means of Microarrays':'Not published.'
,'Dissecting Glucose Signaling with Diversity-Oriented Synthesis and Small-Molecule Microarrays':'Dissecting glucose signalling with diversity-oriented synthesis and small-molecule microarrays'
,'Effects of Microenvironmental Acidosis and Hypoxia on Metastasis':'Not published.'
,'Efficient and Sequence-Specific DNA-Templated Polymerization of PNA Aldehydes':'Efficient and Sequence-Specific DNA-Templated Polymerization of Peptide Nucleic Acid Aldehydes'
,'Electrostatic Stabilization of the Folding Transition State in Single RNA Molecules':'Not appeared to be published'
,'Endocytosis of Influenza Viruses':'Endocytosis of influenza viruses'
,'Enzymatic Tailoring of the Bacterial Siderophore Enterobactin Alters Membrane Partitioning and Iron Acquisition':'Enzymatic tailoring of enterobactin alters membrane partitioning and iron acquisition'
,'Ferroelectric Nanowires':'title'
,'Ferroelectric Phase Transitions in Individual Single-Crystalline BaTiO3 Nanowrires':'Ferroelectric Phase Transition in Individual Single-Crystalline BaTiO3 Nanowires'
,'From the Cover: Transcriptional Regulation of Phagocytosis-Induced Membrane Biogenesis by Sterol Regulatory Element Binding Proteins':'Transcriptional regulation of phagocytosis-induced membrane biogenesis by sterol regulatory element binding proteins'
,'Galectin-1 Induced T Cell Apoptosis at the Human Maternal-Fetal Interface':'T cell apoptosis at the maternal-fetal interface in early human pregnancy, involvement of galectin-1'
,'Genes for Small, Non-Coding RNAs Under Sporulation Control in Bacillus subtilis':'Small Genes under Sporulation Control in the Bacillus subtilis genome'
,'Growth and Pattern of the Mammalian Neural Tube are Governed by Partially Overlapping Feedback Activities of the Hedgehog Antagonists Patched1and Hip1':'Growth and pattern of the mammalian neural tube are governed by partially overlapping feedback activities of the hedgehog antagonists patched 1 and Hhip1'
,'Human Oxoguanine Glycosylase 1: The Case for Catalytic Perfection':'poster'
,'Hydrodynamic Flow-stretching Assay for Single-Molecule Studies of Nucleic Acid-Protein Interactions':'title'
,'Identification of Ald6 as the Target of a Class of Small Molecule Suppressors of FK506 and Their Use in Network Dissection':'Identification of Ald6p as the target of a class of small-molecule suppressors of FK506 and their use in network dissection'
,'Identification of GAPDH as a Protein Target of the Saframycin Class of Natural Antiproliferative Agents':'Identification of GAPDH as a protein target of the saframycin antiproliferative agents'
,'Identification of a Small-Molecule Inhibitor of Class 1a PI3Ks Using Cell-Based Screening':'Identification of a small-molecule inhibitor of class Ia PI3Ks with cell-based screening'
,'Immune Activation of NF- B and JNK Requires Drosophila TAK1':'Immune activation of NF-kappaB and JNK requires Drosophila TAK1'
,'Insulin Staining of ES Cell Progeny Can Result From Insulin Uptake':'Insulin staining of ES cell progeny from insulin uptake'
,'Intracellular Signaling by Receptor Tyrosine Kinases is a Direct Function of Their Recruitment Profiles':'unclear'
,'Investigation of the Catalytic Mechanism of Human 8-Oxoguanine Glycosylase':'unclear'
,'Kedarcidin Chromophore-Synthesis of its Proposed Structure and Evidence for a Streochemical Revision':'Kedarcidin Chromophore-Synthesis of Its Proposed Structure and Evidence for a Stereochemical Revision'
,'Kinetic Analysis of Sequential Multi-Step Reactions':'Kinetic analysis of sequential multistep reactions'
,'Magnetic Switching of Phase-Slip Dissipation in NbSe2 Nanobelts':'Magnetic Switching of Phase-Slip Dissipation in NbSe2 Nanobelts'
,'Members of the miRNA-200 Family Mediate Olfactory Neurogenesis':'Members of the miRNA-200 Family Regulate Olfactory Neurogenesis'
,'Mild Itrosation and Hydrolysis of Polyfunctional Amides':'Mild nitrosation and hydrolysis of polyfunctional amides'
,'Modular Synthesis and Preliminary Biological Evaluation of Stereochemically and Skeletally Diverse 1,3-dioxanes':'Modular synthesis and preliminary biological evaluation of stereochemically diverse 1,3-dioxanes'
,'Motor Neurons Produced from Human Embryonic Stem Cells are Sensitive to a Toxic Effect of Glial Cells Carrying an ALS-Causing SOD1 Mutation':'Human embryonic stem cell-derived motor neurons are sensitive to the toxic effect of glial cells carrying an ALS-causing mutation'
,'Mulitdimensional Chemical Genetic Analysis of a Combinatorial Library of Deacetylase Inhibitors Using Cell-Based Assays':'Multidimensional chemical genetic analysis of diversity-oriented synthesis-derived deacetylase inhibitors using cell-based assays'
,'Multidimensional Chemical Genetic Analysis of a Combinatorial Library of Deacetylase Inhibitors Using Cell-Based Assays':'Multidimensional chemical genetic analysis of diversity-oriented synthesis-derived deacetylase inhibitors using cell-based assays'
,'Multistep Small-Molecule Syntheses Programmed by DNA Templates':'Multistep small-molecule synthesis programmed by DNA templates'
,'NMR Studies of the Catalytic Mechanism of Human 8-OxgGuanine Glycosylase':'poster'
,'Network Motifs: Simple Building Blocks of Complex Networks':'Network motifs: simple building blocks of complex networks'
, 'A New Family of Candidate Pheromone Receptors in Mammals' : 'A novel family of candidate pheromone receptors in mammals'
,'Nonconventional Stereochemical Issues in the Design of the Synthesis of the Vancomycin Antibiotics. Challenges Imposed by Axial and Non-Planar Chiral Elements in the Heptapeptide Aglycons':'Nonconventional Stereochemical Issues in the Design of the Synthesis of the Vancomycin Antibiotics: Challenges Imposed by Axial and Nonplanar Chiral Elements in the Heptapeptide Aglycons'
,'Normal Cells, but Not Cancer Cells, Survive Severe Plk1 Depletion':'Normal Cells, but Not Cancer Cells, Survive Severe Plk1 Depletion'
,'Peroxisome Proliferator-Activated Receptor alpha Antagonism Inhibits Hepatitis C Virus Replication Source':'Peroxisome proliferator-activated receptor alpha antagonism inhibits hepatitis C virus replication'
,'Photodegradation of Congo Red Catalyzed by Nanosized TiO2':'Photodegradation of Congo Red catalyzed by nanosized TiO2'
,'Printing Small Molecules as Microarrays and Detecting Protein-Ligand Interactions en Masse':'Printing Small Molecules as Microarrays and Detecting Protein-Ligand Interactions en Masse'
,'Protein Phosphatase 2A Interacts with the 70-kDa S6 Kinase and is Activated by Inhibition of FKBP12-Rapamycin-Associated Protein':'Protein phosphatase 2A interacts with the 70-kDa S6 kinase and is activated by inhibition of FKBP12-rapamycinassociated protein'
,'Regulation of MLL1 H3 K4 Methyltransferase Activity by its Core Components':'Regulation of MLL1 H3K4 methyltransferase activity by its core components'
,'SMK-1/PPH-4.1 Mediated Silencing of the CHK-1 Response to DNA Damage in Early C. elegans Embryos':'SMK-1/PPH-4.1-mediated silencing of the CHK-1 response to DNA damage in early C. elegans embryos'
,'Single-Crystalline Barium Titanate Nanowires':'title'
,'Single-Crystalline Vanadium Dioxide Nanowires with Rectangular Cross Section':'title'
,'Single-Molecule RNA Folding':'title'
,'Small-Molecule Inhibition of Proteasome and Aggresome Function Induces Synergistic Anti-Tumor Activity in Multiple Myeloma':'title'
,'Solid-Phase Biomimetic Synthesis of Carpanone-Like Molecules':'title'
,'Sox6 Controls the Parcellation of Progenitors and Development of Cortical Interneurons in the Telencephalon':'title'
,'Stereospecific Synthesis of the CP-263,114 Core Structure':'title'
,'Stitching a-Helical Peptides by Tandem Ring-Closing Metathesis':'title'
,'Strain-Induced Self Organization of Metal-Semiconductor Domains in Single-Crystalline VO2 Nanobeams':'title'
,'Studying Vesicle Recycling in Presynaptic Terminals Using the Genetically-Encoded Probe SynaptopHluorin':'title'
,'Supercharging Proteins Can Impart Extraordinary Resilience':'title'
,'Superfamilies of Evolved and Designed Networks':'title'
,'Synthesis of (+)-CP-263,114':'title'
,'Synthesis of (-)-Quinocarcin by Directed Condensation of a-Amino Aldehydes':'title'
,'Synthesis of (-)-Tetracycline':'title'
,'Synthesis of Cyclooctenones Using Intramolecular Hydroacylation':'title'
,'Synthesis of Diaryl Ethers Through the Copper-Promoted Arylation of Phenols with Arylboronic Acids. An Expedient Synthesis of Thyroxine':'title'
,'Synthesis of Single-Crystalline La1-xBaxMnO3 Nanocubes with Adjustable Doping':'title'
,'Synthesis of Single-Crystalline Perovskite Nanowires Composed of Barium Titanate and Strontium Titanate':'title'
,'Synthesis, Conformational Analysis, and Gelation Behavior of C3-Symmetric Donor-Acceptor Molecules':'title'
,'Systematic, RNAi-Mediated Identification of mus-101 Modifier Genes in C. elegans':'title'
,'Taking Drug Discovery Up a Notch: Direct Inhibition of Transcription Factors with Stapled Peptides':'title'
,'Targeting the CR4-CR5 Region of Human Telomerase RNA with RIPtides':'title'
,'The Centromeric Protein Sgo1 Signals Lack of Tension on Mitotic Chromosomes':'title'
,'The Function of IKKepsilon in IFN-mediated Antiviral Immunity':'title'
,'The Sigma(E) Regulon and the Identification of Additional Sporulation Genes in Bacillus subtilis':'title'
,'The Xenopus Mus101 Protein is Required for Recruitment of Cdc45 to Origins of DNA Replication':'title'
,'Total Synthesis of Teicoplanin Aglycon':'title'
,'Total Synthesis of Vancomycin and Eremomycin Aglycons':'title'
,'Towards Diversity-Oriented, Stereoselective Syntheses of Biaryl- or Bis(aryl)metal-Containing Medium Rings':'title'
,'Transition Metal Oxide Nanowires and Devices Incorporating Them':'title'
,'Vapor Phase Synthesis and Characterization of E-FeSi Nanowires':'title'
,'Vesicles and the Spinal Cord':'title'
,'Visualizing Post-Endocytic Traffic of Synaptic Vesicles at Hippocampal Synapses':'title'}